/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Vellora AI and Dragon IDE contributors. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, realpathSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import * as path from 'node:path';
import { test } from 'node:test';
import { admitPlans, confineCommand, confineRequest, confineSpawn, LEFT_OUT, linkedOutside, McpEditor, McpServerConfig, ModelRequest, openCodeFolders, prepareSandbox, sandboxProfile, savedElsewhere, ShellCreating, skillsOutside, toldOutputs, toolchainFolders, withoutOutside } from '../sandbox/sandbox';
import sandboxPlugin from '../sandbox/opencodePlugin';

test('the sandbox profile closes the home folders and other disks to agents\' commands, except the open folders, their home and the toolchains', () => {
	const profile = sandboxProfile({
		folders: ['/Users/ada/game', '/Volumes/Art/assets'],
		home: '/Users/ada/.dragon/sandbox/homes/game-0123',
		readOnly: ['/Users/ada/.bun/bin'],
		closed: ['/Users', '/Users/ada', '/Volumes'],
		sealed: ['/Users/ada/.dragon/sandbox/profiles'],
	});
	assert.deepEqual(profile.split('\n'), [
		'(version 1)',
		'; Generated by Dragon IDE for agents\' shell commands.',
		'(allow default)',
		'(deny file-write*)',
		'(allow file-write* (subpath "/private/tmp") (subpath "/private/var/folders") (subpath "/dev"))',
		'(deny file-read* file-write* (subpath "/Users") (subpath "/Users/ada") (subpath "/Volumes"))',
		'(allow file-read* (literal "/Users") (literal "/Users/ada") (literal "/Users/ada/.bun") (literal "/Users/ada/.dragon") (literal "/Users/ada/.dragon/sandbox") (literal "/Users/ada/.dragon/sandbox/homes") (literal "/Volumes") (literal "/Volumes/Art"))',
		'(allow file-read* (subpath "/Users/ada/.bun/bin"))',
		'(allow file-read* file-write* (subpath "/Users/ada/game") (subpath "/Volumes/Art/assets") (subpath "/Users/ada/.dragon/sandbox/homes/game-0123"))',
		'(deny file-write* (subpath "/Users/ada/.dragon/sandbox/profiles"))',
		'(deny network-outbound (remote unix-socket))',
		'(allow network-outbound (remote unix-socket (path-literal "/private/var/run/mDNSResponder")))',
		'(deny lsopen)',
		'(deny appleevent-send)',
		'(deny mach-lookup (global-name "com.apple.pasteboard.1"))',
		'(deny user-preference-read user-preference-write)',
		'',
	]);
});

test('commands may read the toolchains on PATH in the home folder and the interpreters they link to, and not the folders around them', async () => {
	const home = realpathSync(mkdtempSync(path.join(tmpdir(), 'dragon-toolchains-')));
	try {
		// `~/.local/bin/python3.13` → `…/cpython-3.13/bin/python3.13`, where `cpython-3.13` → `cpython-3.13.14`.
		const store = path.join(home, '.local', 'share', 'uv', 'python');
		mkdirSync(path.join(store, 'cpython-3.13.14', 'bin'), { recursive: true });
		writeFileSync(path.join(store, 'cpython-3.13.14', 'bin', 'python3.13'), '');
		symlinkSync(path.join(store, 'cpython-3.13.14'), path.join(store, 'cpython-3.13'));
		mkdirSync(path.join(home, '.local', 'bin'), { recursive: true });
		symlinkSync(path.join(store, 'cpython-3.13', 'bin', 'python3.13'), path.join(home, '.local', 'bin', 'python3.13'));
		// `~/.cargo` also holds the crates.io token.
		mkdirSync(path.join(home, '.cargo', 'bin'), { recursive: true });
		writeFileSync(path.join(home, '.cargo', 'bin', 'cargo'), '');
		writeFileSync(path.join(home, '.cargo', 'credentials.toml'), '');
		mkdirSync(path.join(home, '.pyenv'));
		mkdirSync(path.join(home, 'notes'));
		const pathEnv = [path.join(home, '.local', 'bin'), path.join(home, '.cargo', 'bin'), '/usr/bin', home, 'relative/bin'].join(path.delimiter);
		assert.deepEqual((await toolchainFolders(pathEnv, home)).map(folder => path.relative(home, folder)), [
			'.cargo/bin',
			'.local/bin',
			'.local/share/uv/python',
			'.local/share/uv/python/cpython-3.13',
			'.local/share/uv/python/cpython-3.13.14',
			'.pyenv',
		]);
	} finally {
		rmSync(home, { recursive: true, force: true });
	}
});

test('a shell command loses the server\'s password and credentials, and runs in the sandbox when there is one', () => {
	const temp = mkdtempSync(path.join(tmpdir(), 'dragon-confine-command-'));
	try {
		const profile = path.join(temp, 'window.sb');
		const wrapper = path.join(temp, 'shell');
		writeFileSync(profile, '(version 1)\n');
		writeFileSync(wrapper, '#!/bin/sh\n');
		const event = (): ShellCreating => ({
			command: 'npm test', cwd: '/Users/ada/game', shell: '/bin/zsh',
			env: {
				PATH: '/usr/bin:/bin', HOME: '/Users/ada', LANG: 'en_US.UTF-8', KEYTIMEOUT: '1', TERM: 'xterm-256color', OPENCODE_TERMINAL: '1',
				OPENCODE_PASSWORD: 'server', OPENCODE_CONFIG_CONTENT: '{}', DRAGON_AGENTS_HUB: '/hub.json', VSCODE_IPC_HOOK: '/ipc.sock', ELECTRON_RUN_AS_NODE: '1',
				SSH_AUTH_SOCK: '/agent.sock', GITHUB_TOKEN: 'ghp', AWS_SECRET_ACCESS_KEY: 'aws', AWS_ACCESS_KEY_ID: 'id', OPENAI_API_KEY: 'sk', NPM_CONFIG__AUTH: 'npm', UNSET: undefined,
			},
		});
		const sandboxed = event();
		const unsandboxed = event();
		const missing = event();
		const results = [
			confineCommand(sandboxed, { DRAGON_SANDBOX_PROFILE: profile, DRAGON_SANDBOX_WRAPPER: wrapper, DRAGON_SANDBOX_HOME: '/Users/ada/.dragon/sandbox/homes/game' }),
			confineCommand(unsandboxed, {}),
			confineCommand(missing, { DRAGON_SANDBOX_PROFILE: path.join(temp, 'gone.sb'), DRAGON_SANDBOX_WRAPPER: wrapper, DRAGON_SANDBOX_HOME: '/Users/ada/.dragon/sandbox/homes/game' }),
		];
		const kept = { PATH: '/usr/bin:/bin', HOME: '/Users/ada', LANG: 'en_US.UTF-8', KEYTIMEOUT: '1', TERM: 'xterm-256color', OPENCODE_TERMINAL: '1' };
		assert.deepEqual({ results, sandboxed, unsandboxed, missing }, {
			results: [undefined, undefined, `the sandbox for shell commands is missing (${path.join(temp, 'gone.sb')}); the command runs outside it`],
			sandboxed: { command: 'npm test', cwd: '/Users/ada/game', shell: wrapper, env: { ...kept, HOME: '/Users/ada/.dragon/sandbox/homes/game', DRAGON_SANDBOX_SHELL: '/bin/zsh', DRAGON_SANDBOX_PROFILE: profile } },
			unsandboxed: { command: 'npm test', cwd: '/Users/ada/game', shell: '/bin/zsh', env: kept },
			missing: { command: 'npm test', cwd: '/Users/ada/game', shell: '/bin/zsh', env: kept },
		});
	} finally {
		rmSync(temp, { recursive: true, force: true });
	}
});

test('a command OpenCode spawns itself, an MCP server or a formatter, is wrapped in the window\'s sandbox when there is one', () => {
	const temp = mkdtempSync(path.join(tmpdir(), 'dragon-confine-spawn-'));
	try {
		const profile = path.join(temp, 'window.sb');
		writeFileSync(profile, '(version 1)\n');
		const home = '/Users/ada/.dragon/sandbox/homes/game';
		const command = ['uvx', 'mcp-server-fetch', '--port', '8080'];
		const results = {
			sandboxed: confineSpawn(command, { DRAGON_SANDBOX_PROFILE: profile, DRAGON_SANDBOX_HOME: home }),
			unsandboxed: confineSpawn(command, {}),
			empty: confineSpawn([], { DRAGON_SANDBOX_PROFILE: profile, DRAGON_SANDBOX_HOME: home }),
			missing: confineSpawn(command, { DRAGON_SANDBOX_PROFILE: path.join(temp, 'gone.sb'), DRAGON_SANDBOX_HOME: home }),
		};
		assert.deepEqual(results, {
			sandboxed: { ok: true, command: ['/usr/bin/sandbox-exec', '-f', profile, 'uvx', 'mcp-server-fetch', '--port', '8080'], home },
			unsandboxed: undefined,
			empty: undefined,
			missing: { ok: false, error: `the sandbox is missing (${path.join(temp, 'gone.sb')}); the command runs outside it` },
		});
	} finally {
		rmSync(temp, { recursive: true, force: true });
	}
});

test('the sandbox plugin runs a project\'s local MCP server in the window\'s sandbox and leaves a remote one alone', async () => {
	const temp = mkdtempSync(path.join(tmpdir(), 'dragon-mcp-transform-'));
	const saved = { DRAGON_CONFINED_FOLDERS: process.env.DRAGON_CONFINED_FOLDERS, DRAGON_SANDBOX_PROFILE: process.env.DRAGON_SANDBOX_PROFILE, DRAGON_SANDBOX_HOME: process.env.DRAGON_SANDBOX_HOME };
	try {
		const workspace = path.join(temp, 'game');
		const profile = path.join(temp, 'window.sb');
		const home = path.join(temp, 'home');
		writeFileSync(profile, '(version 1)\n');
		process.env.DRAGON_CONFINED_FOLDERS = JSON.stringify([workspace]);
		process.env.DRAGON_SANDBOX_PROFILE = profile;
		process.env.DRAGON_SANDBOX_HOME = home;
		// The project's MCP servers: a local one that OpenCode spawns, a remote URL, and a local one whose
		// command is `opencode`, which OpenCode runs with BUN_BE_BUN set.
		const servers = new Map<string, McpServerConfig>([
			['fetch', { type: 'local', command: ['uvx', 'mcp-server-fetch'], environment: { TOKEN: 'keep' } }],
			['brave', { type: 'remote' }],
			['nested', { type: 'local', command: ['opencode', 'x', 'mcp'] }],
		]);
		const editor: McpEditor = {
			list: () => Array.from(servers),
			update: (name, update) => { const config = servers.get(name); if (config) { update(config); } },
		};
		await sandboxPlugin.setup({
			location: { directory: workspace },
			tool: { hook: async () => undefined },
			shell: { hook: async () => undefined },
			mcp: { transform: async callback => { await callback(editor); } },
		});
		assert.deepEqual(Object.fromEntries(servers), {
			fetch: { type: 'local', command: ['/usr/bin/sandbox-exec', '-f', profile, 'uvx', 'mcp-server-fetch'], environment: { TOKEN: 'keep', HOME: home } },
			brave: { type: 'remote' },
			nested: { type: 'local', command: ['/usr/bin/sandbox-exec', '-f', profile, 'opencode', 'x', 'mcp'], environment: { BUN_BE_BUN: '1', HOME: home } },
		});
	} finally {
		for (const [key, value] of Object.entries(saved)) {
			if (value === undefined) {
				delete process.env[key];
			} else {
				process.env[key] = value;
			}
		}
		rmSync(temp, { recursive: true, force: true });
	}
});

test('a file tool call is refused when a link in an open folder leads out of the open folders', () => {
	// Not the real path: on macOS the temp folder is reached through the `/var` link, as an open folder may be.
	const temp = mkdtempSync(path.join(tmpdir(), 'dragon-linked-'));
	const workspace = path.join(temp, 'game');
	const second = path.join(temp, 'assets');
	const outside = path.join(temp, 'private');
	try {
		for (const dir of [workspace, second, outside]) {
			mkdirSync(dir);
		}
		writeFileSync(path.join(workspace, 'hello.txt'), 'hello\n');
		writeFileSync(path.join(outside, 'secret.txt'), 'secret\n');
		symlinkSync(path.join(workspace, 'hello.txt'), path.join(workspace, 'hello-link.txt'));
		symlinkSync(second, path.join(workspace, 'assets'));
		symlinkSync(outside, path.join(workspace, 'out'));
		symlinkSync(path.join(outside, 'secret.txt'), path.join(workspace, 'secret.txt'));
		symlinkSync(path.join(outside, 'authorized_keys'), path.join(workspace, 'keys'));
		const patch = (...files: string[]) => ({ patchText: ['*** Begin Patch', ...files, '+x', '*** End Patch'].join('\n') });
		const inputs: Record<string, unknown> = {
			'a file': { filePath: 'hello.txt' },
			'a file by its real path': { filePath: path.join(realpathSync(workspace), 'hello.txt') },
			'a link to a file in the folder': { filePath: 'hello-link.txt' },
			'a link to the other open folder': { path: 'assets' },
			'a file not made yet': { filePath: 'levels/one.json' },
			'a patch inside': patch('*** Update File: hello.txt', '*** Move to: levels/hello.txt'),
			'a path outside the folders, left to the permission rules': { filePath: path.join(outside, 'secret.txt') },
			'a glob': { pattern: '**/*.txt' },
			'no arguments': undefined,
			'a link to a file outside': { filePath: 'secret.txt' },
			'a file through a link to a folder outside': { filePath: path.join(workspace, 'out', 'secret.txt') },
			'a search through a link to a folder outside': { path: 'out', pattern: 'secret' },
			'a new file through a link to a folder outside': { filePath: 'out/planted.txt' },
			'a link to a file outside not made yet': { file_path: 'keys' },
			'a patch adding a file through a link': patch('*** Update File: hello.txt', '*** Add File: out/planted.txt'),
			'a patch moving a file through a link': patch('*** Update File: hello.txt', '*** Move to: out/hello.txt'),
		};
		const outcomes = Object.fromEntries(Object.entries(inputs).map(([name, input]) => [name, linkedOutside(workspace, input, [workspace, second]) ?? 'allowed']));
		assert.deepEqual(outcomes, {
			'a file': 'allowed',
			'a file by its real path': 'allowed',
			'a link to a file in the folder': 'allowed',
			'a link to the other open folder': 'allowed',
			'a file not made yet': 'allowed',
			'a patch inside': 'allowed',
			'a path outside the folders, left to the permission rules': 'allowed',
			'a glob': 'allowed',
			'no arguments': 'allowed',
			'a link to a file outside': 'secret.txt leads outside the folders open in the window through a symbolic link. Agents are kept to those folders.',
			'a file through a link to a folder outside': `${path.join(workspace, 'out', 'secret.txt')} leads outside the folders open in the window through a symbolic link. Agents are kept to those folders.`,
			'a search through a link to a folder outside': 'out leads outside the folders open in the window through a symbolic link. Agents are kept to those folders.',
			'a new file through a link to a folder outside': 'out/planted.txt leads outside the folders open in the window through a symbolic link. Agents are kept to those folders.',
			'a link to a file outside not made yet': 'keys leads outside the folders open in the window through a symbolic link. Agents are kept to those folders.',
			'a patch adding a file through a link': 'out/planted.txt leads outside the folders open in the window through a symbolic link. Agents are kept to those folders.',
			'a patch moving a file through a link': 'out/hello.txt leads outside the folders open in the window through a symbolic link. Agents are kept to those folders.',
		});
	} finally {
		rmSync(temp, { recursive: true, force: true });
	}
});

test('a link in OpenCode\'s own folders that agents are let into, or one reached from the home folder, does not take a file tool out of them', () => {
	const temp = mkdtempSync(path.join(tmpdir(), 'dragon-linked-'));
	const home = path.join(temp, 'home');
	const workspace = path.join(home, 'game');
	const outside = path.join(home, 'private');
	const opencode = openCodeFolders({ home, tmpdir: path.join(temp, 'tmp') });
	try {
		for (const dir of [workspace, outside, opencode.tmp, opencode.plan]) {
			mkdirSync(dir, { recursive: true });
		}
		writeFileSync(path.join(outside, 'secret.txt'), 'secret\n');
		writeFileSync(path.join(opencode.tmp, 'notes.txt'), 'notes\n');
		// A command may make links in OpenCode's temp folder.
		symlinkSync(outside, path.join(opencode.tmp, 'out'));
		symlinkSync(outside, path.join(opencode.plan, 'out'));
		symlinkSync(outside, path.join(workspace, 'out'));
		const inputs: Record<string, unknown> = {
			'a file in the temp folder': { filePath: path.join(opencode.tmp, 'notes.txt') },
			'a new plan': { filePath: '~/.opencode/plan/levels.md' },
			'a file from the home folder in an open folder': { filePath: '~/game/levels.json' },
			'the home folder, left to the permission rules': { path: '~' },
			'a file through a link in the temp folder': { filePath: path.join(opencode.tmp, 'out', 'secret.txt') },
			'a search through a link in the plan folder': { path: '~/.opencode/plan/out', pattern: 'secret' },
			'a file from the home folder through a link in an open folder': { filePath: '~/game/out/secret.txt' },
		};
		const reachable = [workspace, opencode.tmp, opencode.plan];
		assert.deepEqual(Object.fromEntries(Object.entries(inputs).map(([name, input]) => [name, linkedOutside(workspace, input, reachable, home) ?? 'allowed'])), {
			'a file in the temp folder': 'allowed',
			'a new plan': 'allowed',
			'a file from the home folder in an open folder': 'allowed',
			'the home folder, left to the permission rules': 'allowed',
			'a file through a link in the temp folder': `${path.join(opencode.tmp, 'out', 'secret.txt')} leads outside the folders open in the window through a symbolic link. Agents are kept to those folders.`,
			'a search through a link in the plan folder': '~/.opencode/plan/out leads outside the folders open in the window through a symbolic link. Agents are kept to those folders.',
			'a file from the home folder through a link in an open folder': '~/game/out/secret.txt leads outside the folders open in the window through a symbolic link. Agents are kept to those folders.',
		});
	} finally {
		rmSync(temp, { recursive: true, force: true });
	}
});

test('output OpenCode saved is open to the window whose models it told of it, and no other\'s, nor the folders it is kept in', () => {
	// Not the real path, and a home folder whose name holds a space.
	const temp = mkdtempSync(path.join(tmpdir(), 'dragon-saved-'));
	const home = path.join(temp, 'Ada Lovelace');
	const workspace = path.join(home, 'game');
	const opencode = openCodeFolders({ home, tmpdir: path.join(temp, 'tmp') });
	const saved = [opencode.toolOutput, opencode.shell];
	const mine = path.join(opencode.toolOutput, 'tool_0ffd7fd12001Mine0000000000');
	const other = path.join(opencode.toolOutput, 'tool_0ffd7fd12001Other000000000');
	const mineShell = path.join(opencode.shell, '54be5e0b5febd6a2', 'sh_0ffd7fd12001Mine0000000.out');
	const global = path.join(opencode.shell, 'global');
	try {
		for (const file of [mine, other, mineShell, path.join(global, 'sh_0ffd7fd12001Other000000.out')]) {
			mkdirSync(path.dirname(file), { recursive: true });
			writeFileSync(file, 'output\n');
		}
		mkdirSync(workspace);
		symlinkSync(other, path.join(workspace, 'other.txt'));
		symlinkSync(mine, path.join(workspace, 'mine.txt'));
		// Wherever the request's format keeps its texts; the model itself names a folder it guessed.
		const request = {
			system: [{ type: 'text', text: 'You are an agent.' }],
			messages: [
				{ role: 'tool', content: [{ type: 'tool-result', output: { type: 'content', value: [{ type: 'text', text: `finding 1\n[showing lines 1-5 of 14; full output saved to ${mine}]` }] } }] },
				{ role: 'tool', content: `16\n20\n\n[showing lines 16-20 of 20; full output saved to ${realpathSync(mineShell)}]` },
				{ role: 'assistant', content: [{ type: 'text', text: `I will look in ${global} and ${opencode.toolOutput}/ next.` }] },
			],
		};
		const told = toldOutputs(request, saved);
		const inputs: Record<string, unknown> = {
			'its own tool output': { filePath: mine },
			'its own tool output, from the home folder': { filePath: `~/${path.relative(home, mine)}` },
			'its own shell output': { filePath: mineShell },
			'its own output through a link': { filePath: 'mine.txt' },
			'a file in an open folder': { filePath: 'levels.json' },
			'no arguments': undefined,
			'another window\'s tool output': { filePath: other },
			'another project\'s shell output': { filePath: path.join(global, 'sh_0ffd7fd12001Other000000.out') },
			'another\'s output through a link': { filePath: 'other.txt' },
			'the folder of tool output': { path: opencode.toolOutput },
			'a folder the model named': { path: global },
			'a new file there': { filePath: path.join(opencode.toolOutput, 'planted') },
		};
		assert.deepEqual({
			told: told.map(file => path.relative(temp, file)).sort(),
			outcomes: Object.fromEntries(Object.entries(inputs).map(([name, input]) => [name, savedElsewhere(workspace, input, saved, told, home)?.replace(/^.* is not/, '… is not') ?? 'allowed'])),
		}, {
			told: [path.relative(temp, global), path.relative(temp, mine), path.relative(temp, realpathSync(mineShell))].sort(),
			outcomes: {
				'its own tool output': 'allowed',
				'its own tool output, from the home folder': 'allowed',
				'its own shell output': 'allowed',
				'its own output through a link': 'allowed',
				'a file in an open folder': 'allowed',
				'no arguments': 'allowed',
				'another window\'s tool output': '… is not output OpenCode saved for this window. Agents are kept to the folders open in the window and their own output.',
				'another project\'s shell output': '… is not output OpenCode saved for this window. Agents are kept to the folders open in the window and their own output.',
				'another\'s output through a link': '… is not output OpenCode saved for this window. Agents are kept to the folders open in the window and their own output.',
				'the folder of tool output': '… is not output OpenCode saved for this window. Agents are kept to the folders open in the window and their own output.',
				'a folder the model named': '… is not output OpenCode saved for this window. Agents are kept to the folders open in the window and their own output.',
				'a new file there': '… is not output OpenCode saved for this window. Agents are kept to the folders open in the window and their own output.',
			},
		});
	} finally {
		rmSync(temp, { recursive: true, force: true });
	}
});

test('a plan is open to the windows it was written from, and no other\'s, nor the folder every project keeps its plans in', () => {
	const temp = mkdtempSync(path.join(tmpdir(), 'dragon-plans-'));
	const home = path.join(temp, 'home');
	const game = path.join(home, 'game');
	const shop = path.join(home, 'shop');
	const opencode = openCodeFolders({ home, tmpdir: path.join(temp, 'tmp') });
	const plans = { plans: opencode.plan, records: path.join(home, '.dragon', 'sandbox', 'plans') };
	const plan = (name: string) => path.join(opencode.plan, name);
	const outcomes: Record<string, string> = {};
	// A window on `folders` calls a tool from the first; a write it is let make, it makes.
	const call = (name: string, folders: readonly string[], tool: string, input: Record<string, string>) => {
		const problem = admitPlans(folders[0], tool, input, plans, folders, home);
		outcomes[name] = problem?.replace(/^\S+ is/, '… is').replaceAll(realpathSync(temp), '') ?? 'allowed';
		if (!problem && tool === 'write') {
			writeFileSync(path.resolve(folders[0], input.filePath.replace(/^~/, home)), input.content);
		}
	};
	try {
		for (const dir of [game, shop, opencode.plan]) {
			mkdirSync(dir, { recursive: true });
		}
		// Written before Dragon recorded plans, or by OpenCode outside Dragon.
		writeFileSync(plan('old.md'), 'old\n');
		symlinkSync(plan('levels.md'), path.join(shop, 'levels.md'));
		call('the game lists the plans before any is recorded', [game], 'read', { filePath: opencode.plan });
		call('the game writes a new plan', [game], 'write', { filePath: plan('levels.md'), content: 'levels\n' });
		call('the game reads it', [game], 'read', { filePath: plan('levels.md') });
		call('the game reads it from the home folder', [game], 'read', { filePath: '~/.opencode/plan/levels.md' });
		call('a window on the shop and the game reads it', [shop, game], 'read', { filePath: plan('levels.md') });
		call('the shop reads it', [shop], 'read', { filePath: plan('levels.md') });
		call('the shop reads it through a link', [shop], 'read', { filePath: 'levels.md' });
		call('the shop changes it', [shop], 'edit', { filePath: '~/.opencode/plan/levels.md', oldString: 'levels', newString: 'prices' });
		call('the shop patches it', [shop], 'patch', { patchText: `*** Begin Patch\n*** Update File: ${plan('levels.md')}\n@@\n-levels\n+prices\n*** End Patch` });
		call('a window on a folder in the game reads it', [path.join(game, 'src')], 'read', { filePath: plan('levels.md') });
		call('the shop writes a new plan', [shop], 'write', { filePath: plan('prices.md'), content: 'prices\n' });
		call('the shop reads a plan not made yet', [shop], 'read', { filePath: plan('ghost.md') });
		call('the shop reads a plan from before', [shop], 'read', { filePath: plan('old.md') });
		call('the game lists the plans', [game], 'read', { filePath: opencode.plan });
		call('the shop searches the plans', [shop], 'grep', { path: '~/.opencode/plan', pattern: 'levels' });
		call('a window on the home folder reads a plan from before', [home], 'read', { filePath: plan('old.md') });
		rmSync(plan('levels.md'));
		call('the shop writes a plan of the name the game deleted', [shop], 'write', { filePath: plan('levels.md'), content: 'prices\n' });
		call('the game reads the shop\'s plan of that name', [game], 'read', { filePath: plan('levels.md') });
		call('the game lists the plans, none of them its own', [game], 'read', { filePath: opencode.plan });
		const records = readdirSync(plans.records).map(name => JSON.parse(readFileSync(path.join(plans.records, name), 'utf8')) as { file: string; folders: string[] });
		assert.deepEqual({
			outcomes,
			records: records.map(({ file, folders }) => [path.basename(file), ...folders.map(folder => path.relative(realpathSync(temp), folder))].join(' ')).sort(),
		}, {
			outcomes: {
				'the game lists the plans before any is recorded': '… is a folder of plans, which every project shares. Agents are kept to the plans written from the folders open in the window, and there are none yet.',
				'the game writes a new plan': 'allowed',
				'the game reads it': 'allowed',
				'the game reads it from the home folder': 'allowed',
				'a window on the shop and the game reads it': 'allowed',
				'the shop reads it': '… is a plan not written from the folders open in the window. Agents are kept to the plans written from them.',
				'the shop reads it through a link': '… is a plan not written from the folders open in the window. Agents are kept to the plans written from them.',
				'the shop changes it': '… is a plan not written from the folders open in the window. Agents are kept to the plans written from them.',
				'the shop patches it': '… is a plan not written from the folders open in the window. Agents are kept to the plans written from them.',
				'a window on a folder in the game reads it': '… is a plan not written from the folders open in the window. Agents are kept to the plans written from them.',
				'the shop writes a new plan': 'allowed',
				'the shop reads a plan not made yet': 'allowed',
				'the shop reads a plan from before': '… is a plan not written from the folders open in the window. Agents are kept to the plans written from them.',
				'the game lists the plans': `… is a folder of plans, which every project shares. Agents are kept to the plans written from the folders open in the window: ${path.join(path.sep, 'home', '.opencode', 'plan', 'levels.md')}.`,
				'the shop searches the plans': `… is a folder of plans, which every project shares. Agents are kept to the plans written from the folders open in the window: ${path.join(path.sep, 'home', '.opencode', 'plan', 'prices.md')}.`,
				'a window on the home folder reads a plan from before': 'allowed',
				'the shop writes a plan of the name the game deleted': 'allowed',
				'the game reads the shop\'s plan of that name': '… is a plan not written from the folders open in the window. Agents are kept to the plans written from them.',
				'the game lists the plans, none of them its own': '… is a folder of plans, which every project shares. Agents are kept to the plans written from the folders open in the window, and there are none yet.',
			},
			records: [`levels.md ${path.join('home', 'shop')}`, `prices.md ${path.join('home', 'shop')}`],
		});
	} finally {
		rmSync(temp, { recursive: true, force: true });
	}
});

test('what OpenCode sends the model loses the instruction files and skills from outside the open folders, and keeps its own', () => {
	const skill = (id: string) => `  <skill>\n    <id>${id}</id>\n    <name>${id}</name>\n    <description>About ${id}.</description>\n  </skill>`;
	const outside = new Map([
		['/home/ada/.config/opencode/AGENTS.md', 'GLOBAL\n'],
		// Changed since OpenCode read it: out up to what OpenCode sends next.
		['/home/ada/AGENTS.md', 'PARENT, now\n'],
		['/home/ada/notes/AGENTS.md', 'NOTES\n'],
		['/home/ada/a+b (old)/AGENTS.md', undefined],
	]);
	const skills = ['home-skill', 'late-skill'];
	const system = [
		'Intro.\n\n\n',
		'Instructions from: /home/ada/.config/opencode/AGENTS.md\nGLOBAL\n',
		// OpenCode joins them with a line break: a file that does not end in one runs into the next.
		'Instructions from: /home/ada/AGENTS.md\nPARENT, as read',
		'Instructions from: /home/ada/game/AGENTS.md\nPROJECT\n\n\n',
		'Skills provide specialized instructions and workflows for specific tasks.\n<available_skills>\n',
		`${skill('opencode')}\n${skill('home-skill')}\n${skill('project-skill')}\n</available_skills>`,
	].join('\n');
	const update = [
		'<system-update>',
		'The instructions from /home/ada/a+b (old)/AGENTS.md no longer apply.',
		'New instructions apply from:',
		'Instructions from: /home/ada/notes/AGENTS.md',
		'NOTES',
		'The instructions from /home/ada/.config/opencode/AGENTS.md changed. Here\'s the diff:',
		'```diff',
		'@@ -1 +1,2 @@',
		' GLOBAL',
		'+GLOBAL, again',
		'```',
		'The instructions changed:',
		'Instructions from: /home/ada/game/AGENTS.md',
		'PROJECT',
		'PROJECT, again',
		'',
		'New skills are available in addition to those previously listed:',
		skill('late-skill'),
		'The following skill IDs are no longer available and must not be used: home-skill, old-skill.',
		'</system-update>',
	].join('\n');
	assert.deepEqual({
		system: withoutOutside(system, outside, skills),
		update: withoutOutside(update, outside, skills),
		onlyOutside: withoutOutside('Instructions from: /home/ada/AGENTS.md\nPARENT, as read\n', outside, skills),
		gone: withoutOutside('<system-update>\nThe following skill IDs are no longer available and must not be used: late-skill.\n</system-update>', outside, skills),
		empty: withoutOutside('', outside, skills),
	}, {
		system: [
			'Intro.\n\n\n',
			'Instructions from: /home/ada/game/AGENTS.md\nPROJECT\n\n\n',
			'Skills provide specialized instructions and workflows for specific tasks.\n<available_skills>\n',
			`${skill('opencode')}\n${skill('project-skill')}\n</available_skills>`,
		].join('\n'),
		update: [
			'<system-update>',
			'The instructions changed:',
			'Instructions from: /home/ada/game/AGENTS.md',
			'PROJECT',
			'PROJECT, again',
			'',
			'The following skill IDs are no longer available and must not be used: old-skill.',
			'</system-update>',
		].join('\n'),
		onlyOutside: LEFT_OUT,
		gone: '<system-update>\n</system-update>',
		empty: '',
	});
});

test('a model request loses the instruction files and skills outside the open folders, found through links too', () => {
	// Not resolved: the temp folder is a link on macOS.
	const temp = mkdtempSync(path.join(tmpdir(), 'dragon-request-'));
	const real = realpathSync(temp);
	try {
		const files: Record<string, string> = {
			'home/AGENTS.md': 'PARENT\n',
			'home/.config/opencode/AGENTS.md': 'GLOBAL\n',
			'home/elsewhere/AGENTS.md': 'ELSEWHERE\n',
			'home/.claude/skills/home-skill/SKILL.md': 'HOME SKILL\n',
			'home/elsewhere/linked-skill/SKILL.md': 'LINKED SKILL\n',
			'home/game/AGENTS.md': 'PROJECT\n',
			'home/game/.claude/skills/project-skill/SKILL.md': 'PROJECT SKILL\n',
		};
		for (const [file, content] of Object.entries(files)) {
			mkdirSync(path.dirname(path.join(temp, file)), { recursive: true });
			writeFileSync(path.join(temp, file), content);
		}
		const game = path.join(temp, 'home', 'game');
		symlinkSync(path.join(temp, 'home', 'elsewhere'), path.join(game, 'linked'));
		symlinkSync(path.join(temp, 'home', 'elsewhere', 'linked-skill'), path.join(game, '.claude', 'skills', 'linked-skill'));
		// OpenCode names files by their real paths; the one through the link, as it reached it.
		const named = (file: string) => path.join(real, file);
		const skills = skillsOutside([
			{ id: 'opencode', path: '/builtin/opencode.md' },
			{ id: 'home-skill', path: named('home/.claude/skills/home-skill/SKILL.md') },
			{ id: 'project-skill', path: named('home/game/.claude/skills/project-skill/SKILL.md') },
			{ id: 'linked-skill', path: named('home/game/.claude/skills/linked-skill/SKILL.md') },
		], [game]);
		const request: ModelRequest = {
			system: [
				{ type: 'text', text: [named('home/.config/opencode/AGENTS.md'), named('home/AGENTS.md'), named('home/game/AGENTS.md')].map(file => `Instructions from: ${file}\n${readFileSync(file, 'utf8')}`).join('\n') },
				{ type: 'text', text: `Instructions from: ${named('home/game/linked/AGENTS.md')}\nELSEWHERE\n` },
			],
			messages: [
				{ content: [{ type: 'text', text: `<system-update>\nThe instructions from ${named('home/AGENTS.md')} no longer apply.\nThe instructions from ${named('home/game/AGENTS.md')} no longer apply.\n</system-update>` }, { type: 'image' }] },
				{ content: 'Plain text.' },
			],
		};
		confineRequest(request, [game], skills);
		assert.deepEqual({ skills, request: JSON.parse(JSON.stringify(request).replaceAll(real, '<temp>')) }, {
			skills: ['home-skill', 'linked-skill'],
			request: {
				system: [
					{ type: 'text', text: 'Instructions from: <temp>/home/game/AGENTS.md\nPROJECT\n' },
					{ type: 'text', text: LEFT_OUT },
				],
				messages: [
					{ content: [{ type: 'text', text: '<system-update>\nThe instructions from <temp>/home/game/AGENTS.md no longer apply.\n</system-update>' }, { type: 'image' }] },
					{ content: 'Plain text.' },
				],
			},
		});
	} finally {
		rmSync(temp, { recursive: true, force: true });
	}
});

test('in the sandbox, a command reaches the open folders and its own home, and nothing else in the home folder', { skip: process.platform !== 'darwin' && 'macOS only' }, async () => {
	const temp = realpathSync(mkdtempSync(path.join(tmpdir(), 'dragon-sandbox-')));
	// The home folder is in the temp folder, which commands may write to; the home folder still wins.
	const home = path.join(temp, 'home');
	const workspace = path.join(home, 'game');
	const second = path.join(temp, 'assets');
	const outside = path.join(home, 'private');
	try {
		for (const dir of [workspace, second, outside]) {
			mkdirSync(dir, { recursive: true });
		}
		writeFileSync(path.join(workspace, 'hello.txt'), 'hello\n');
		writeFileSync(path.join(outside, 'secret.txt'), 'secret\n');
		const outcomes = async (folders: string[], commands: readonly string[]) => {
			const prepared = await prepareSandbox({ folders, home, pathEnv: process.env.PATH ?? '', closed: [] });
			assert.ok(prepared.ok, JSON.stringify(prepared));
			const { DRAGON_SANDBOX_PROFILE, DRAGON_SANDBOX_WRAPPER, DRAGON_SANDBOX_HOME } = prepared.variables;
			return Object.fromEntries(commands.map(command => {
				const run = spawnSync(DRAGON_SANDBOX_WRAPPER, ['-c', command], {
					cwd: folders[0], encoding: 'utf8', timeout: 20_000,
					env: { PATH: process.env.PATH, HOME: DRAGON_SANDBOX_HOME, DRAGON_SANDBOX_SHELL: '/bin/sh', DRAGON_SANDBOX_PROFILE },
				});
				return [command, run.status === 0 ? 'ran' : 'refused'];
			}));
		};
		const profiles = path.join(home, '.dragon', 'sandbox', 'profiles');
		assert.deepEqual({
			open: await outcomes([workspace, second], [
				'cat hello.txt',
				'echo made > made.txt',
				`echo art > ${second}/art.txt`,
				'echo mine > "$HOME/mine.txt" && cat "$HOME/mine.txt"',
				'cat ../private/secret.txt',
				`ls ${outside}`,
				'echo planted > ../private/planted.txt',
				`echo changed >> ${profiles}/shell`,
			]),
			// With the home folder itself open, the sandbox's own files still cannot be changed.
			home: await outcomes([home], ['cat private/secret.txt', `echo changed >> ${profiles}/shell`]),
			planted: existsSync(path.join(outside, 'planted.txt')),
			wrapper: readFileSync(path.join(profiles, 'shell'), 'utf8').includes('changed'),
		}, {
			open: {
				'cat hello.txt': 'ran',
				'echo made > made.txt': 'ran',
				[`echo art > ${second}/art.txt`]: 'ran',
				'echo mine > "$HOME/mine.txt" && cat "$HOME/mine.txt"': 'ran',
				'cat ../private/secret.txt': 'refused',
				[`ls ${outside}`]: 'refused',
				'echo planted > ../private/planted.txt': 'refused',
				[`echo changed >> ${profiles}/shell`]: 'refused',
			},
			home: { 'cat private/secret.txt': 'ran', [`echo changed >> ${profiles}/shell`]: 'refused' },
			planted: false,
			wrapper: false,
		});
	} finally {
		rmSync(temp, { recursive: true, force: true });
	}
});
