/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Vellora AI and Dragon IDE contributors. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/*
 * The macOS sandbox agents' shell commands run in. OpenCode's file tools are kept to the folders
 * open in the window by permission rules (`confinementConfig`); a shell command reaches whatever
 * its process can, so on macOS each one runs under `sandbox-exec` with a profile that closes the
 * home folders and other disks except for the open folders. The sandbox plugin
 * (`opencodePlugin.ts`) swaps the command's shell for a wrapper that does this.
 *
 * This module does not import `vscode`: the plugin and the tests use it too.
 */

import { execFile } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, readlinkSync, realpathSync, renameSync, statSync, writeFileSync } from 'node:fs';
import { chmod, mkdir, readdir, readFile, readlink, realpath, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import * as path from 'node:path';

const SANDBOX_EXEC = '/usr/bin/sandbox-exec';

export interface SandboxProfileInput {
	/** The folders commands may read and write: those open in the window, their worktrees and Git folders. Real paths. */
	readonly folders: readonly string[];
	/** The home folder commands are given in place of the real one. A real path. */
	readonly home: string;
	/** Folders commands may read but not change: the toolchains in the home folder that are on `PATH`. Real paths. */
	readonly readOnly: readonly string[];
	/** Folders closed to commands except for the ones above: the home folders and other disks. Real paths. */
	readonly closed: readonly string[];
	/** Folders no command may change, even inside an open folder: the sandbox's own profile. Real paths. */
	readonly sealed?: readonly string[];
}

/** A path as a sandbox profile string. */
function quote(value: string): string {
	return `"${value.replace(/[\\"]/g, c => `\\${c}`)}"`;
}

function inside(parent: string, child: string): boolean {
	const rel = path.relative(parent, child);
	return rel === '' || (!rel.startsWith('..') && !path.isAbsolute(rel));
}

/**
 * The sandbox profile for agents' shell commands. Everything else a process may do stays allowed,
 * so compilers, package managers and dev servers work as usual, but:
 * - nothing under a closed folder is read or written, except the open folders, the command's own
 *   home folder and the toolchains on `PATH`; the folders above them can be listed, which Git and
 *   Node need;
 * - nothing is written outside those folders and the temp folders;
 * - no Unix socket is connected to, which keeps commands from Docker, ssh-agent and the editor,
 *   except the one name lookups go through;
 * - no app is opened and no Apple event sent, which would run code outside the sandbox;
 * - the clipboard and apps' preferences (`defaults`), which macOS serves from outside the
 *   process, are not read.
 */
export function sandboxProfile(input: SandboxProfileInput): string {
	const writable = [...input.folders, input.home];
	const ancestors = new Set<string>();
	for (const folder of [...writable, ...input.readOnly]) {
		for (const root of input.closed.filter(root => inside(root, folder))) {
			for (let dir = path.dirname(folder); inside(root, dir); dir = path.dirname(dir)) {
				ancestors.add(dir);
				if (dir === root) {
					break;
				}
			}
		}
	}
	const subpaths = (folders: Iterable<string>) => [...folders].map(folder => `(subpath ${quote(folder)})`).join(' ');
	const literals = (folders: Iterable<string>) => [...folders].map(folder => `(literal ${quote(folder)})`).join(' ');
	return [
		'(version 1)',
		'; Generated by Dragon IDE for agents\' shell commands.',
		'(allow default)',
		// A later rule wins over an earlier one.
		'(deny file-write*)',
		'(allow file-write* (subpath "/private/tmp") (subpath "/private/var/folders") (subpath "/dev"))',
		...(input.closed.length ? [`(deny file-read* file-write* ${subpaths(input.closed)})`] : []),
		...(ancestors.size ? [`(allow file-read* ${literals([...ancestors].sort())})`] : []),
		...(input.readOnly.length ? [`(allow file-read* ${subpaths(input.readOnly)})`] : []),
		`(allow file-read* file-write* ${subpaths(writable)})`,
		...(input.sealed?.length ? [`(deny file-write* ${subpaths(input.sealed)})`] : []),
		'(deny network-outbound (remote unix-socket))',
		'(allow network-outbound (remote unix-socket (path-literal "/private/var/run/mDNSResponder")))',
		'(deny lsopen)',
		'(deny appleevent-send)',
		'(deny mach-lookup (global-name "com.apple.pasteboard.1"))',
		'(deny user-preference-read user-preference-write)',
		'',
	].join('\n');
}

/** The symbolic links met on the way to the file a path names: following them means reading them. */
async function linksOnTheWay(file: string): Promise<string[]> {
	const links: string[] = [];
	let pending = file.split(path.sep).filter(part => part);
	let current: string = path.sep;
	for (let hops = 0; pending.length && hops < 40;) {
		const next = path.join(current, pending.shift()!);
		const target = await readlink(next).catch(() => undefined);
		if (target === undefined) {
			current = next;
			continue;
		}
		hops++;
		links.push(next);
		pending = [...path.resolve(current, target).split(path.sep).filter(part => part), ...pending];
		current = path.sep;
	}
	return links;
}

/**
 * Where version managers keep the interpreters in the home folder. A project's virtual environment
 * or `.nvmrc` runs one that is not on `PATH`. They hold programs, not the user's files.
 */
const INTERPRETERS = ['.local/share/uv/python', '.pyenv', '.nvm', '.volta', '.rustup', '.asdf/installs', '.local/share/mise/installs', '.sdkman/candidates'];

/**
 * The folders in the home folder that commands need to read to run the tools there: each folder on
 * `PATH` in the home folder, the folders its links point into (`~/.local/bin/python3.13` links to
 * `…/cpython-3.13/bin/python3.13`, a link to `…/cpython-3.13.14/bin/python3.13`, whose library is
 * in `…/cpython-3.13.14/lib`), and the version managers' interpreters. Not the folders around them:
 * `~/.cargo` also holds the crates.io token. Real paths.
 */
export async function toolchainFolders(pathEnv: string, home: string): Promise<string[]> {
	const realHome = await realpath(home).catch(() => home);
	const folders = new Set<string>();
	for (const entry of pathEnv.split(path.delimiter).filter(entry => path.isAbsolute(entry))) {
		const real = await realpath(entry).catch(() => undefined);
		if (!real || real === realHome || !inside(realHome, real)) {
			continue;
		}
		folders.add(real);
		for (const name of await readdir(real).catch(() => [])) {
			const target = await realpath(path.join(real, name)).catch(() => undefined);
			if (target && !inside(real, target)) {
				const dir = path.dirname(target);
				folders.add(path.basename(dir) === 'bin' ? path.dirname(dir) : dir);
				for (const link of await linksOnTheWay(path.join(real, name))) {
					if (!inside(real, link)) {
						folders.add(link);
					}
				}
			}
		}
	}
	for (const store of INTERPRETERS) {
		const real = await realpath(path.join(realHome, store)).catch(() => undefined);
		if (real) {
			folders.add(real);
		}
	}
	return [...folders].sort();
}

/** Server variables a command must not see: the server's password, Dragon's and the editor's handles. */
const PRIVATE_PREFIXES = /^(OPENCODE_|DRAGON_|VSCODE_|ELECTRON_)/;
/** Variables that look like credentials, which a project's commands get from the project instead. */
const CREDENTIAL = /(^|_)(TOKEN|SECRET|PASSWORD|PASSWD|PASSPHRASE|CREDENTIALS?|API_?KEY|ACCESS_KEY|PRIVATE_KEY|AUTH)(_|$)/i;
const AGENT_SOCKETS = new Set(['SSH_AUTH_SOCK', 'GPG_AGENT_INFO']);

/**
 * The environment for an agent's shell command, from the server's: without the server's password
 * (which would open OpenCode's API, and every file through it), Dragon's and the editor's handles,
 * agent sockets and variables that look like credentials. `OPENCODE_TERMINAL`, which OpenCode sets
 * for its commands, stays.
 */
export function commandEnv(env: Readonly<Record<string, string | undefined>>): Record<string, string> {
	const result: Record<string, string> = {};
	for (const [name, value] of Object.entries(env)) {
		if (value === undefined || AGENT_SOCKETS.has(name) || CREDENTIAL.test(name) || (PRIVATE_PREFIXES.test(name) && name !== 'OPENCODE_TERMINAL')) {
			continue;
		}
		result[name] = value;
	}
	return result;
}

/** The arguments OpenCode's and Dragon's file tools take a path in. */
const PATH_ARGUMENTS = ['path', 'filePath', 'file_path'];
/** The files a patch adds, changes, deletes or moves to. */
const PATCH_FILE = /^\*\*\* (?:(?:Add|Update|Delete) File|Move to): (?<file>.+)$/gm;

/** The paths one tool call names: its path arguments and the files its patch touches. */
function toolPaths(input: unknown): string[] {
	if (typeof input !== 'object' || input === null) {
		return [];
	}
	const args = input as Record<string, unknown>;
	const paths = PATH_ARGUMENTS.map(name => args[name]).filter((value): value is string => typeof value === 'string' && !!value.trim());
	if (typeof args.patchText === 'string') {
		paths.push(...[...args.patchText.matchAll(PATCH_FILE)].map(match => match.groups!.file.trim()));
	}
	return paths;
}

/** Where a path really leads: through every link, also one to a file not made yet. */
function realTarget(file: string, hops = 0): string {
	try {
		return realpathSync(file);
	} catch {
		// Missing, or a link to something missing, which writing it would make.
	}
	if (hops < 40) {
		try {
			return realTarget(path.resolve(path.dirname(file), readlinkSync(file)), hops + 1);
		} catch {
			// not a link
		}
	}
	const parent = path.dirname(file);
	return parent === file ? file : path.join(realTarget(parent, hops), path.basename(file));
}

/** A path as OpenCode's file tools take it: from the session's folder, `~` the home folder. */
function toolTarget(directory: string, value: string, home: string): string {
	const fromHome = value === '~' || value.startsWith('~/') || (process.platform === 'win32' && value.startsWith('~\\'));
	return path.resolve(directory, fromHome ? path.join(home, value.slice(2)) : value);
}

/**
 * Why a file tool call may not run: a path it names is in one of `folders` (the open folders, and
 * OpenCode's own that agents are let into) but a symbolic link there leads outside them, say one a
 * command made to `~/.ssh`. OpenCode's rules see only the path as written, and its tools follow
 * links. Paths outside the folders are left to those rules.
 */
export function linkedOutside(directory: string, input: unknown, folders: readonly string[], home = homedir()): string | undefined {
	const real = folders.map(folder => realTarget(folder));
	for (const value of toolPaths(input)) {
		const file = toolTarget(directory, value, home);
		if (![...folders, ...real].some(folder => inside(folder, file))) {
			continue;
		}
		if (!real.some(folder => inside(folder, realTarget(file)))) {
			return `${value} leads outside the folders open in the window through a symbolic link. Agents are kept to those folders.`;
		}
	}
	return undefined;
}

/** The folders of OpenCode's own that agents' file tools are let into (`confinementConfig`). */
export interface OpenCodeFolders {
	/** Where OpenCode saves long tool output, for every window and every project. */
	readonly toolOutput: string;
	/** Where it saves long shell output, a folder for each project. */
	readonly shell: string;
	/** Its temp folder, which it tells agents to use. */
	readonly tmp: string;
	/** Where the plan agent writes plans. */
	readonly plan: string;
}

/**
 * OpenCode's folders as its `Global` paths name them, for a server with these home, temp and data
 * folders: its data folder is in the home folder, its plan folder in its own home folder
 * (`OPENCODE_TEST_HOME`, when that is set).
 */
export function openCodeFolders(input: { readonly home: string; readonly tmpdir: string; readonly dataHome?: string; readonly openCodeHome?: string }): OpenCodeFolders {
	const data = path.join(input.dataHome || path.join(input.home, '.local', 'share'), 'opencode');
	return { toolOutput: path.join(data, 'tool-output'), shell: path.join(data, 'shell'), tmp: path.join(input.tmpdir, 'opencode'), plan: path.join(input.openCodeHome || input.home, '.opencode', 'plan') };
}

/** Every string in a value: the texts of a model request, wherever its format keeps them. */
function stringsIn(value: unknown, found: string[] = [], seen = new Set<object>()): string[] {
	if (typeof value === 'string') {
		found.push(value);
	} else if (typeof value === 'object' && value !== null && !seen.has(value)) {
		seen.add(value);
		for (const item of Object.values(value)) {
			stringsIn(item, found, seen);
		}
	}
	return found;
}

/**
 * The files in `saved` (where OpenCode saves long output) that a model request names: the output
 * OpenCode told the model it saved, `[… full output saved to <file>]`, which it may read.
 */
export function toldOutputs(request: unknown, saved: readonly string[]): string[] {
	const roots = [...new Set(saved.flatMap(folder => [folder, realTarget(folder)]))].map(root => root + path.sep);
	const told = new Set<string>();
	for (const text of stringsIn(request)) {
		for (const root of roots) {
			for (let at = text.indexOf(root); at >= 0; at = text.indexOf(root, at + root.length)) {
				// The folder as it is, as a home folder's name may hold a space; then the file's own name. Not
				// the folder found inside a longer path, as `/var/…` is in `/private/var/…`.
				const name = /^[^\s\]"'`<>|]*/.exec(text.slice(at + root.length))![0];
				if (name && (at === 0 || !/[\w.~/\\-]/.test(text[at - 1]))) {
					told.add(root + name);
				}
			}
		}
	}
	return [...told];
}

/**
 * Why a file tool call may not run: a path it names is in `saved`, where OpenCode saves long output
 * for every window and every project, but is not a file this window's models were told of
 * (`toldOutputs`). Those files' names cannot be guessed, so another's output stays closed as long
 * as the folders there are, which a read would list.
 */
export function savedElsewhere(directory: string, input: unknown, saved: readonly string[], told: Iterable<string>, home = homedir()): string | undefined {
	const roots = saved.flatMap(folder => [folder, realTarget(folder)]);
	let open: Set<string> | undefined;
	for (const value of toolPaths(input)) {
		const file = toolTarget(directory, value, home);
		const real = realTarget(file);
		if (!roots.some(root => inside(root, file) || inside(root, real))) {
			continue;
		}
		open ??= new Set([...told].map(name => realTarget(name)));
		// Never a folder, which would list others' output: a model could name one, whose name can be guessed, itself.
		if (!open.has(real) || statSync(real, { throwIfNoEntry: false })?.isDirectory()) {
			return `${value} is not output OpenCode saved for this window. Agents are kept to the folders open in the window and their own output.`;
		}
	}
	return undefined;
}

/** OpenCode's plan folder, and where Dragon records which folders each plan there was written from. */
export interface PlanFolder {
	/** Where the plan agent writes plans, a folder every project shares. */
	readonly plans: string;
	/** Where Dragon records the folders open in the window that wrote each plan: a folder no agent reaches. */
	readonly records: string;
}

/** What Dragon records of a plan. Real paths. */
interface PlanRecord {
	readonly file: string;
	readonly folders: readonly string[];
}

/** OpenCode's tools that make a file. */
const WRITERS = new Set(['write', 'edit', 'patch']);

/** A plan's record, by the plan's real path. */
function planRecord(records: string, file: string): string {
	return path.join(records, `${createHash('sha256').update(file).digest('hex').slice(0, 32)}.json`);
}

/** The record in a record file; none for one being written, or broken. */
function readPlanRecord(record: string): PlanRecord | undefined {
	try {
		const { file, folders }: Partial<PlanRecord> = JSON.parse(readFileSync(record, 'utf8'));
		return typeof file === 'string' && Array.isArray(folders) ? { file, folders: folders.filter(folder => typeof folder === 'string') } : undefined;
	} catch {
		return undefined;
	}
}

/** Whether a plan was written from a folder open in the window (real paths), or one in it. */
function writtenFrom(record: PlanRecord | undefined, open: readonly string[]): boolean {
	return !!record?.folders.some(folder => open.some(own => inside(own, folder)));
}

/**
 * Admits a file tool call to OpenCode's plan folder, which every project shares. Returns why the
 * call may not run: a path it names there is a plan not written from the folders open in the window,
 * as Dragon recorded, or a folder, which a read would list. Otherwise records the new plans the call
 * writes as written from those folders. A plan written before Dragon recorded them, or by OpenCode
 * outside Dragon, stays closed. When the plan folder is in an open folder, it is open as that is.
 */
export function admitPlans(directory: string, tool: string, input: unknown, plan: PlanFolder, folders: readonly string[], home = homedir()): string | undefined {
	const roots = [plan.plans, realTarget(plan.plans)];
	const open = folders.map(folder => realTarget(folder));
	if (open.some(folder => inside(folder, roots[1]))) {
		return undefined;
	}
	const made: string[] = [];
	for (const value of toolPaths(input)) {
		const file = toolTarget(directory, value, home);
		const real = realTarget(file);
		if (!roots.some(root => inside(root, file) || inside(root, real))) {
			continue;
		}
		const stat = statSync(real, { throwIfNoEntry: false });
		if (stat?.isDirectory()) {
			// None recorded yet, before the first plan: then the folder has no records.
			const names = existsSync(plan.records) ? readdirSync(plan.records) : [];
			const own = names
				.filter(name => name.endsWith('.json'))
				.map(name => readPlanRecord(path.join(plan.records, name)))
				.filter((record): record is PlanRecord => writtenFrom(record, open) && existsSync(record!.file))
				.map(record => record.file)
				.sort();
			return `${value} is a folder of plans, which every project shares. Agents are kept to the plans written from the folders open in the window${own.length ? `: ${own.join(', ')}` : ', and there are none yet'}.`;
		}
		if (!stat) {
			if (WRITERS.has(tool)) {
				made.push(real);
			}
		} else if (!writtenFrom(readPlanRecord(planRecord(plan.records, real)), open)) {
			return `${value} is a plan not written from the folders open in the window. Agents are kept to the plans written from them.`;
		}
	}
	for (const file of made) {
		mkdirSync(plan.records, { recursive: true });
		const record = planRecord(plan.records, file);
		const writing = `${record}.${process.pid}.tmp`;
		writeFileSync(writing, JSON.stringify({ file, folders: open } satisfies PlanRecord));
		renameSync(writing, record);
	}
	return undefined;
}

/** A skill as OpenCode lists it. */
export interface SkillEntry {
	readonly id: string;
	readonly path: string;
}

/** The path OpenCode gives its own skills, built into the binary. */
const BUILT_IN_SKILL = /^\/builtin\//;

/** True when `file` is outside the folders open in the window, through any link on its way. */
export function outsideFolders(file: string, folders: readonly string[]): boolean {
	const target = realTarget(file);
	return !folders.some(folder => inside(realTarget(folder), target));
}

/**
 * The skills outside the folders open in the window, such as the user's own in `~/.claude/skills`,
 * or reached from them through a link. OpenCode's own, built into it, are not.
 */
export function skillsOutside(skills: readonly SkillEntry[], folders: readonly string[]): string[] {
	return skills.filter(skill => !BUILT_IN_SKILL.test(skill.path) && outsideFolders(skill.path, folders)).map(skill => skill.id);
}

/** A text part of a model request, as OpenCode's `session` → `context` hook gives it. */
interface RequestPart {
	readonly type: string;
	text?: string;
}

/** The model request OpenCode's `session` → `context` hook gives, which the hook may rewrite. */
export interface ModelRequest {
	readonly system: readonly RequestPart[];
	readonly messages: readonly { readonly content?: unknown }[];
}

/** OpenCode's heading over an instruction file it sends, and its notices that one changed or went. */
const INSTRUCTION_PATHS = /^(?:Instructions from: (?<file>.+)|The instructions from (?<notice>.+?) (?:no longer apply\.|changed\. Here's the diff:))$/gm;
/** Where the next thing OpenCode sends starts, after an instruction file (it joins them with a line break). */
const AFTER_INSTRUCTIONS = /\n+(?=Instructions from: |New instructions apply from:\n|The instructions from |The instructions changed:\n|Skills provide specialized instructions|The available skills have changed|New skills are available)/g;
/** The headings OpenCode puts over an instruction file that is new or changed. */
const INSTRUCTION_NOTICES = ['New instructions apply from:\n', 'The instructions changed:\n'];
/** OpenCode's notice that skills went, and the ids it lists. */
const GONE_SKILLS_LEAD = 'The following skill IDs are no longer available and must not be used: ';
const GONE_SKILLS = new RegExp(`^${GONE_SKILLS_LEAD}(?<ids>.+)\\.$`, 'gm');
/** What is left of a text that held only instructions or skills from outside the folders. Some providers refuse an empty text. */
export const LEFT_OUT = 'Instructions and skills from outside the folders open in the window were left out.';

/** `value` matched as it is in a regular expression. */
function escapeRegExp(value: string): string {
	return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** `text` without `start`..`end`, the line breaks around it as wide as the wider of the two, and none at either end. */
function cut(text: string, start: number, end: number): string {
	const before = text.slice(0, start).replace(/\n+$/, '');
	const after = text.slice(end).replace(/^\n+/, '');
	if (!before || !after) {
		return before + after;
	}
	return before + '\n'.repeat(Math.max(start - before.length, text.length - end - after.length)) + after;
}

/** `text` without what `pattern` (global) matches. */
function cutAll(text: string, pattern: RegExp): string {
	let result = text;
	pattern.lastIndex = 0;
	for (let match = pattern.exec(result); match; pattern.lastIndex = 0, match = pattern.exec(result)) {
		result = cut(result, match.index, match.index + match[0].length);
	}
	return result;
}

/**
 * Takes out of a text OpenCode sends the model the instruction files and skills it found outside the
 * folders open in the window. OpenCode reads its global AGENTS.md and the AGENTS.md in every folder
 * from the open one up to the home folder itself, with no setting to stop it, and lists the user's own
 * skills (`~/.claude/skills`, `~/.agents/skills`, its config folder's).
 *
 * @param instructions Each instruction file outside the folders, and what it holds now: the exact text
 * comes out; one changed since OpenCode read it comes out up to what OpenCode sends after it.
 * @param skills The ids of the skills outside the folders.
 */
export function withoutOutside(text: string, instructions: ReadonlyMap<string, string | undefined>, skills: readonly string[]): string {
	let result = text;
	for (const [file, content] of instructions) {
		const escaped = escapeRegExp(file);
		result = cutAll(result, new RegExp(`^The instructions from ${escaped} changed\\. Here's the diff:\\n\`\`\`diff\\n[\\s\\S]*?\\n\`\`\`$`, 'gm'));
		result = cutAll(result, new RegExp(`^The instructions from ${escaped} no longer apply\\.$`, 'gm'));
		const heading = `Instructions from: ${file}\n`;
		for (let start = result.indexOf(heading); start >= 0; start = result.indexOf(heading)) {
			let end: number;
			if (content !== undefined && result.startsWith(heading + content, start)) {
				end = start + heading.length + content.length;
			} else {
				AFTER_INSTRUCTIONS.lastIndex = start + heading.length;
				end = AFTER_INSTRUCTIONS.exec(result)?.index ?? result.length;
			}
			const notice = INSTRUCTION_NOTICES.find(notice => start >= notice.length && result.startsWith(notice, start - notice.length));
			result = cut(result, start - (notice?.length ?? 0), end);
		}
	}
	if (skills.length) {
		for (const id of skills) {
			result = cutAll(result, new RegExp(`^[ \\t]*<skill>\\n[ \\t]*<id>${escapeRegExp(id)}</id>\\n[\\s\\S]*?</skill>$`, 'gm'));
		}
		result = cutAll(result, /^New skills are available in addition to those previously listed:$(?!\n[ \t]*<skill>)/gm);
		for (const match of [...result.matchAll(GONE_SKILLS)].reverse()) {
			const left = match.groups!.ids.split(', ').filter(id => !skills.includes(id));
			const end = match.index + match[0].length;
			result = left.length ? `${result.slice(0, match.index)}${GONE_SKILLS_LEAD}${left.join(', ')}.${result.slice(end)}` : cut(result, match.index, end);
		}
	}
	return result || !text ? result : LEFT_OUT;
}

/**
 * Rewrites a model request, as OpenCode's `session` → `context` hook allows, without the instruction
 * files and skills outside the folders open in the window (`withoutOutside`): its system prompt, and
 * the text OpenCode adds to the conversation when instructions or skills change.
 */
export function confineRequest(request: ModelRequest, folders: readonly string[], skills: readonly string[]): void {
	const parts = [...request.system, ...request.messages.flatMap(message => Array.isArray(message.content) ? message.content as RequestPart[] : [])]
		.filter(part => part?.type === 'text' && typeof part.text === 'string');
	const files = [...new Set(parts.flatMap(part => [...part.text!.matchAll(INSTRUCTION_PATHS)].map(match => match.groups!.file ?? match.groups!.notice)))]
		.filter(file => path.isAbsolute(file) && outsideFolders(file, folders));
	if (!files.length && !skills.length) {
		return;
	}
	const instructions = new Map(files.map(file => {
		try {
			return [file, readFileSync(file, 'utf8')] as const;
		} catch {
			return [file, undefined] as const;
		}
	}));
	for (const part of parts) {
		part.text = withoutOutside(part.text!, instructions, skills);
	}
}

/** The variables the server passes to the sandbox plugin. */
export interface SandboxVariables {
	readonly DRAGON_SANDBOX_PROFILE: string;
	readonly DRAGON_SANDBOX_WRAPPER: string;
	readonly DRAGON_SANDBOX_HOME: string;
}

/** The mutable `shell` → `create.before` event OpenCode sends plugins before it spawns a command. */
export interface ShellCreating {
	command: string;
	cwd: string;
	shell: string;
	env: Record<string, string | undefined>;
}

/** A project's local MCP server: a command OpenCode spawns. A remote server is a URL, with no command. */
export interface McpLocalConfig {
	type: 'local';
	command: string[];
	environment?: Record<string, string>;
}
export interface McpRemoteConfig {
	type: 'remote';
}
export type McpServerConfig = McpLocalConfig | McpRemoteConfig;

/** The part of OpenCode's `mcp.transform` editor the sandbox uses: list the servers, and rewrite a local one's command. */
export interface McpEditor {
	list(): readonly (readonly [string, McpServerConfig])[];
	update(name: string, update: (config: McpServerConfig) => void): void;
}

/**
 * Prepares one command: its environment loses what `commandEnv` drops, and, when the server was
 * given a sandbox, the command runs in it, with its own home folder. A sandbox whose files are gone
 * is not used, so commands keep working; it says why.
 */
export function confineCommand(event: ShellCreating, server: Readonly<Record<string, string | undefined>>): string | undefined {
	event.env = commandEnv(event.env);
	const profile = server.DRAGON_SANDBOX_PROFILE;
	const wrapper = server.DRAGON_SANDBOX_WRAPPER;
	const home = server.DRAGON_SANDBOX_HOME;
	if (!profile || !wrapper || !home) {
		return undefined;
	}
	if (!existsSync(profile) || !existsSync(wrapper)) {
		return `the sandbox for shell commands is missing (${existsSync(profile) ? wrapper : profile}); the command runs outside it`;
	}
	event.env = { ...event.env, HOME: home, DRAGON_SANDBOX_SHELL: event.shell, DRAGON_SANDBOX_PROFILE: profile };
	event.shell = wrapper;
	return undefined;
}

/**
 * Runs a command OpenCode spawns directly, not through the shell hook — a project's local MCP server
 * or a formatter — in the window's sandbox, as an agent's shell command is run. It prepends
 * `sandbox-exec` with the window's profile to the command, so the process is kept to the open
 * folders, and gives the home folder to set so `~` resolves inside the sandbox. It returns nothing
 * when there is no sandbox (off macOS, or Full Access, where the server was given none), so the
 * command runs as before; and a reason when the sandbox's files are gone, so the caller can say why
 * and let the command run rather than break it. `command[0]` is the executable.
 */
export function confineSpawn(command: readonly string[], server: Readonly<Record<string, string | undefined>>): { ok: true; command: string[]; home: string } | { ok: false; error: string } | undefined {
	const profile = server.DRAGON_SANDBOX_PROFILE;
	const home = server.DRAGON_SANDBOX_HOME;
	if (!profile || !home || !command.length) {
		return undefined;
	}
	if (!existsSync(profile)) {
		return { ok: false, error: `the sandbox is missing (${profile}); the command runs outside it` };
	}
	return { ok: true, command: [SANDBOX_EXEC, '-f', profile, ...command], home };
}

/** The wrapper OpenCode runs as the command's shell: it runs the real shell, with its arguments, in the sandbox. */
const WRAPPER = [
	'#!/bin/sh',
	'# Generated by Dragon IDE. Runs an agent\'s shell command in the sandbox Dragon made for its window.',
	'shell=$DRAGON_SANDBOX_SHELL',
	'profile=$DRAGON_SANDBOX_PROFILE',
	'unset DRAGON_SANDBOX_SHELL DRAGON_SANDBOX_PROFILE',
	`exec ${SANDBOX_EXEC} -f "$profile" "$shell" "$@"`,
	'',
].join('\n');

export interface PrepareSandboxInput {
	/** The folders open in the window and the folders of their agents' worktrees. */
	readonly folders: readonly string[];
	/** The real home folder. The profile, the wrapper and the commands' home folder are kept in it. */
	readonly home: string;
	readonly pathEnv: string;
	/** Folders closed besides the home folder. Default: `/Users` and `/Volumes`. */
	readonly closed?: readonly string[];
}

/** A folder's real path, also for one not made yet, such as a worktrees folder before the first worktree. */
function realFolder(folder: string): string {
	try {
		return realpathSync(folder);
	} catch {
		const parent = path.dirname(folder);
		return parent === folder ? folder : path.join(realFolder(parent), path.basename(folder));
	}
}

function run(file: string, args: readonly string[], cwd?: string, env?: NodeJS.ProcessEnv): Promise<{ code: number; stdout: string; stderr: string }> {
	return new Promise(resolve => {
		execFile(file, args, { cwd, env, timeout: 10_000 }, (err, stdout, stderr) => {
			resolve({ code: err ? (typeof err.code === 'number' ? err.code : 1) : 0, stdout: String(stdout), stderr: String(stderr || (err && !stderr ? err.message : '')) });
		});
	});
}

/**
 * Writes the profile, the wrapper and the commands' home folder for a window's folders, and checks
 * that `sandbox-exec` runs with them. Returns the variables for the server, or why there is no
 * sandbox: then commands run outside it, as they would without Dragon.
 */
export async function prepareSandbox(input: PrepareSandboxInput): Promise<{ ok: true; variables: SandboxVariables } | { ok: false; error: string }> {
	if (!existsSync(SANDBOX_EXEC)) {
		return { ok: false, error: `${SANDBOX_EXEC} was not found` };
	}
	const home = realFolder(input.home);
	const open = [...new Set(input.folders.map(realFolder))];
	// A folder may be a worktree of a repository elsewhere; Git needs the repository's folder.
	const gitFolders = await Promise.all(open.map(async folder => {
		const result = await run('git', ['rev-parse', '--path-format=absolute', '--git-common-dir'], folder);
		return result.code === 0 && result.stdout.trim() ? realFolder(result.stdout.trim()) : undefined;
	}));
	const folders = [...new Set([...open, ...gitFolders.filter((folder): folder is string => !!folder)])].sort();
	const id = createHash('sha1').update(folders.join('\n')).digest('hex').slice(0, 12);
	// In the closed home folder, so that no command changes the profile or the wrapper.
	const dir = path.join(home, '.dragon', 'sandbox');
	const commandHome = path.join(dir, 'homes', `${path.basename(open[0] ?? 'scratch')}-${id}`);
	await mkdir(commandHome, { recursive: true });
	// Commits made by agents keep the author's name; nothing else of the real Git config is read.
	const identity = await Promise.all(['user.name', 'user.email'].map(async key => [key, (await run('git', ['config', '--global', '--get', key])).stdout.trim()] as const));
	const gitconfig = identity.filter(([, value]) => value).map(([key, value]) => `\t${key.split('.')[1]} = ${JSON.stringify(value)}\n`).join('');
	await writeFile(path.join(commandHome, '.gitconfig'), gitconfig ? `[user]\n${gitconfig}` : '', 'utf8');
	const profile = sandboxProfile({
		folders,
		home: commandHome,
		readOnly: await toolchainFolders(input.pathEnv, home),
		closed: [...new Set([home, ...(input.closed ?? ['/Users', '/Volumes']).map(realFolder)])].sort(),
		// Also when the home folder itself is open.
		sealed: [path.join(dir, 'profiles')],
	});
	await mkdir(path.join(dir, 'profiles'), { recursive: true });
	const profileFile = path.join(dir, 'profiles', `${id}.sb`);
	const wrapper = path.join(dir, 'profiles', 'shell');
	await writeFile(profileFile, profile, 'utf8');
	if ((await readFile(wrapper, 'utf8').catch(() => undefined)) !== WRAPPER) {
		await writeFile(wrapper, WRAPPER, 'utf8');
	}
	await chmod(wrapper, 0o755);
	const probe = await run(wrapper, ['-c', 'exit 0'], undefined, { DRAGON_SANDBOX_SHELL: '/bin/sh', DRAGON_SANDBOX_PROFILE: profileFile });
	if (probe.code !== 0) {
		return { ok: false, error: `sandbox-exec did not run a command with the profile: ${probe.stderr.trim() || `exit ${probe.code}`}` };
	}
	return { ok: true, variables: { DRAGON_SANDBOX_PROFILE: profileFile, DRAGON_SANDBOX_WRAPPER: wrapper, DRAGON_SANDBOX_HOME: commandHome } };
}
