/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Vellora AI and Dragon IDE contributors. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import * as path from 'node:path';
import { pathToFileURL } from 'node:url';
import { splashProvider, SplashModel } from './localAI/splash';
import { ollamaConfig, OllamaModel } from './ollama/ollama';
import type { PermissionRule } from './opencode/types';

/**
 * OpenCode allows every tool by default. Dragon's permission modes decide file edits and shell
 * commands in the chat (Ask shows the approval prompt, Full Access approves it, Read-Only denies
 * it), so OpenCode has to ask for them first.
 */
const ASK_PERMISSIONS: readonly PermissionRule[] = [
	{ action: 'edit', resource: '*', effect: 'ask' },
	{ action: 'shell', resource: '*', effect: 'ask' },
];

/**
 * The plan agent's own edit rules (from OpenCode's `opencode.plan` plugin), restated: config rules
 * come after an agent's rules, so the `edit` question above would otherwise replace its denial.
 */
const PLAN_PERMISSIONS: readonly PermissionRule[] = [
	{ action: 'edit', resource: '*', effect: 'deny' },
	{ action: 'edit', resource: '~/.opencode/plan/*', effect: 'allow' },
];

/**
 * Session rules for Read-Only. OpenCode checks session denials before the commands a user chose
 * to "Always allow", and drops wholly denied tools from what the model is offered. Subagents run in
 * sessions of their own without these rules, so only the explore agent, which only reads, may run.
 */
export const READ_ONLY_PERMISSIONS: readonly PermissionRule[] = [
	{ action: 'edit', resource: '*', effect: 'deny' },
	{ action: 'shell', resource: '*', effect: 'deny' },
	{ action: 'subagent', resource: '*', effect: 'deny' },
	{ action: 'subagent', resource: 'explore', effect: 'allow' },
];

export interface DragonConfigInput {
	/** `provider/model` chosen in onboarding or `dragon.model`. */
	readonly model?: string;
	readonly ollamaOrigin: string;
	readonly ollamaModels: readonly OllamaModel[];
	readonly splashModels?: readonly SplashModel[];
	/** Directory of the Instant Grep OpenCode plugin, when enabled. */
	readonly searchPluginDir?: string;
	/** Directory of the agent messaging OpenCode plugin, when it was built. */
	readonly agentsPluginDir?: string;
}

/**
 * Builds the OpenCode config layer Dragon IDE owns. It is merged by OpenCode on top of the
 * user's own `opencode.json`, and OpenCode watches the file, so edits apply without a restart.
 */
export function buildDragonConfig(input: DragonConfigInput): object {
	const plugins = [input.searchPluginDir, input.agentsPluginDir].filter((dir): dir is string => !!dir);
	return {
		$schema: 'https://opencode.ai/config.json',
		...(input.model ? { model: input.model } : {}),
		providers: {
			...(ollamaConfig(input.ollamaOrigin, input.ollamaModels) as { providers: object }).providers,
			...(input.splashModels?.length ? { splash: splashProvider(input.splashModels) } : {}),
		},
		...(plugins.length ? { plugins } : {}),
		permissions: ASK_PERMISSIONS,
		agents: { plan: { permissions: PLAN_PERMISSIONS } },
	};
}

/**
 * Writes the directory OpenCode loads one of Dragon's plugins from (Instant Grep by default).
 * OpenCode wants a plugin directory with an `index` entry; it re-exports the compiled plugin
 * shipped with the extension.
 */
export async function writeSearchPlugin(dir: string, compiledPlugin: string, name = 'Instant Grep'): Promise<void> {
	await mkdir(dir, { recursive: true });
	const entry = `// Generated by Dragon IDE. Loads the ${name} plugin shipped with the dragon-agent extension.\nexport { default } from ${JSON.stringify(pathToFileURL(compiledPlugin).href)};\n`;
	const file = path.join(dir, 'index.mjs');
	const current = await readFile(file, 'utf8').catch(() => undefined);
	if (current !== entry) {
		await writeFile(file, entry, 'utf8');
	}
}

/** Writes the config file only when its content changed, so OpenCode is not reloaded for nothing. */
export async function writeDragonConfig(file: string, config: object): Promise<boolean> {
	const next = JSON.stringify(config, null, '\t') + '\n';
	const current = await readFile(file, 'utf8').catch(() => undefined);
	if (current === next) {
		return false;
	}
	await mkdir(path.dirname(file), { recursive: true });
	await writeFile(file, next, 'utf8');
	return true;
}
